# General configuration
nameOverride: &nameOverride yaml-ws-online-session

partOf: &partOf yaml-online

repository: &repository
  url: https://github.com/caiomedeirospinto/yaml-ws-online-session.git
  ref: develop
  path: ./

healthcheck: &healthcheck
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1

# Deployment as code con estrategia Serverless
deployment:
  servicePort: 8080
  nameOverride: *nameOverride
  partOf: *partOf
  repository: *repository
  runtime:
    name: quarkus
    version: "21.2"
  readinessProbe: *healthcheck
  livenessProbe: *healthcheck
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 50Mi

# Pipeline as code
# ci-cd:
